# Iris Plugin Configuration

# Command Cooldowns (in minutes)
cooldowns:
  food: 15
  heal: 30
  wolves: 30

# Food Command Settings
food:
  beef_amount: 8
  chicken_amount: 8
  pork_amount: 8

# Messages
messages:
  food_received: "&aYou have received raw meat!"
  cooldown_message: "&cYou must wait %time% before using this command again!"