name: iris-plugin
version: '1.0-SNAPSHOT'
main: org.duoKeyboardKoalition.irisPlugin.IrisPlugin
api-version: '1.21'
commands:
  heal:
    description: Heals the player to full health.
    usage: /heal
  wolves:
    description: Summons 5 loyal wolves.
    usage: /wolves
  food:
    description: Gives the player raw meat.
    usage: /food
  livestock:
    description: Summons a sheep, pig, and mooshroom.
    usage: /livestock